name: Run ESLint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=18.16.0"
          check-latest: true

      - name: Install dependencies
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
          npm install

      - name: Run ESLint
        run: |
          npm run lint
