name: Migrate and publish demo site

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  migrate-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout demo site
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DEPLOY_REPO }}
          ref: ${{ secrets.DEPLOY_BRANCH }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: demo-site

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=18.16.0"
          check-latest: true

      - name: Install dependencies
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
          npm install

      - name: Configure environment
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Migrate
        run: |
          export ROOT_DIR="$(pwd)/demo-site"
          export COMMIT_SHA_SHORT="$(git rev-parse --short HEAD)"
          node App/migrate_ci.js

      - name: Publish
        run: |
          cd demo-site
          git add .
          git commit -m "Auto-commit from CI: ${GITHUB_SHA}"
          git push
